name: Build on push to main

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
          dotnet-quality: 'preview'
      - name: Build projects
        run: |
          if [ -n "$PSVersionTable" ]; then
                    # Running on Windows using PowerShell
                    $tag = git rev-parse --short $env:GITHUB_SHA
                    $release_name = "App-$tag-win-x64"

                    # Build everything
                    dotnet publish -p:PublishSingleFile=true --self-contained true --runtime "win-x64" -c Release -o $release_name

                    # Pack files
                    if ("win-x64" -eq "win-x64") {
                              # Pack to zip for Windows
                              & 7z a -tzip "$($release_name).zip" "$($release_name)\*"
                    } else {
                              echo "Unknown platform"
                              exit 1
                    }

                    # Delete output directory
                    Remove-Item -Recurse $release_name
          else
                    # Running on Unix using Bash
                    tag=$(git rev-parse --short "$GITHUB_SHA")
                    release_name="App-$tag-win-x64"

                    # Build everything
                    dotnet publish -p:PublishSingleFile=true --self-contained true --runtime "win-x64" -c Release -o "$release_name"

                    # Pack files
                    if [ "win-x64" == "win-x64" ]; then
                              # Pack to zip for Windows
                              7z a -tzip "${release_name}.zip" "./${release_name}/*"
                    else
                              echo "Unknown platform"
                              exit 1
                    }

                    # Delete output directory
                    rm -r "$release_name"
          fi
